/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "SBIconViewDelegate-Protocol.h"

@protocol STKGroupViewDelegate <SBIconViewDelegate>
- (_Bool)groupView:(id)arg1 shouldRecognizeGesturesSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)shouldGroupViewOpen:(id)arg1;

@optional
- (void)groupViewWillBeDestroyed:(id)arg1;
- (void)groupViewDidClose:(id)arg1;
- (void)groupViewWillClose:(id)arg1;
- (void)groupViewDidOpen:(id)arg1;
- (void)groupViewWillOpen:(id)arg1;
- (void)groupView:(id)arg1 didMoveToOffset:(double)arg2;
@end

