/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class SBIconView, SBScaleIconZoomAnimator, STKSelectionView;

@interface STKGroupSelectionAnimator : NSObject
{
    STKSelectionView *_selectionView;
    SBIconView *_iconView;
    SBScaleIconZoomAnimator *_zoomAnimator;
    double _startScale;
    struct CGPoint _startCenter;
}

- (void)closeSelectionViewAnimatedWithCompletion:(id)arg1;
- (void)openSelectionViewAnimatedWithCompletion:(id)arg1;
- (void)dealloc;
- (id)initWithSelectionView:(id)arg1 iconView:(id)arg2;

@end

