/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "STKGroupViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSCache, NSMutableArray, STKGroupSelectionAnimator, STKGroupView, STKIconViewRecycler, STKSelectionView, UISwipeGestureRecognizer, UITapGestureRecognizer, UIView;

@interface STKGroupController : NSObject <STKGroupViewDelegate, UIGestureRecognizerDelegate>
{
    STKGroupView *_openGroupView;
    UIView *_listDimmingView;
    UISwipeGestureRecognizer *_closeSwipeRecognizer;
    UITapGestureRecognizer *_closeTapRecognizer;
    STKGroupSelectionAnimator *_selectionAnimator;
    STKSelectionView *_selectionView;
    struct STKGroupSlot _selectionSlot;
    NSMutableArray *_iconsToShow;
    NSMutableArray *_iconsToHide;
    _Bool _openGroupViewWasModified;
    _Bool _wasLongPressed;
    _Bool _hasInfiniBoard;
    _Bool _hasInfinidock;
    _Bool _hasCylinder;
    STKIconViewRecycler *_recycler;
    NSCache *_groupCache;
    STKGroupView *_openingGroupView;
}

+ (id)sharedController;
@property(readonly, nonatomic) STKGroupView *openingGroupView; // @synthesize openingGroupView=_openingGroupView;
@property(readonly, nonatomic) STKGroupView *openGroupView; // @synthesize openGroupView=_openGroupView;
- (void)forwardInvocation:(id)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)__selectorIsPartOfIconViewDelegateProtocol:(SEL)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)icon:(id)arg1 touchEnded:(_Bool)arg2;
- (void)icon:(id)arg1 touchMoved:(id)arg2;
- (void)iconTouchBegan:(id)arg1;
- (void)iconHandleLongPress:(id)arg1;
- (_Bool)iconShouldAllowTap:(id)arg1;
- (void)iconTapped:(id)arg1;
- (void)groupViewWillBeDestroyed:(id)arg1;
- (void)groupViewDidClose:(id)arg1;
- (void)groupViewWillClose:(id)arg1;
- (void)groupViewDidOpen:(id)arg1;
- (void)groupView:(id)arg1 didMoveToOffset:(double)arg2;
- (void)groupViewWillOpen:(id)arg1;
- (_Bool)groupView:(id)arg1 shouldRecognizeGesturesSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)shouldGroupViewOpen:(id)arg1;
- (void)_prefsChanged;
- (void)_closeSelectionView;
- (void)_selectIconForCurrentSlot:(id)arg1;
- (void)_showSelectionViewForIconView:(id)arg1;
- (void)_closeOpenGroupOrSelectionView;
- (void)_removeCloseGestureRecognizers;
- (void)_addCloseGestureRecognizers;
- (void)_setDimStrength:(double)arg1;
- (void)_removeDimmingView;
- (void)_setupDimmingView;
- (id)_currentScrollView;
- (void)_setAllowScrolling:(_Bool)arg1;
- (id)_activeGroupView;
- (id)_groupWithEmptySlotsForIcon:(id)arg1;
- (void)handleIconRemoval:(id)arg1;
- (void)handleStatusBarTap;
- (_Bool)handleClosingEvent:(unsigned long long)arg1;
- (void)performRotationWithDuration:(double)arg1;
- (void)removeGroupViewFromIconView:(id)arg1;
- (void)addOrUpdateGroupViewForIconView:(id)arg1;
- (id)init;

@end

