/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@class NSArray, NSMutableArray;

@interface STKGroupLayout : NSObject <NSFastEnumeration>
{
    NSMutableArray *_topIcons;
    NSMutableArray *_bottomIcons;
    NSMutableArray *_leftIcons;
    NSMutableArray *_rightIcons;
    NSMutableArray *_unknownIcons;
}

+ (id)layoutWithIconsAtTop:(id)arg1 bottom:(id)arg2 left:(id)arg3 right:(id)arg4;
@property(readonly, nonatomic) NSArray *rightIcons; // @synthesize rightIcons=_rightIcons;
@property(readonly, nonatomic) NSArray *leftIcons; // @synthesize leftIcons=_leftIcons;
@property(readonly, nonatomic) NSArray *bottomIcons; // @synthesize bottomIcons=_bottomIcons;
@property(readonly, nonatomic) NSArray *topIcons; // @synthesize topIcons=_topIcons;
//- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)setObject:(id)arg1 atIndexedSubscript:(unsigned long long)arg2;
- (id)objectAtIndexedSubscript:(unsigned long long)arg1;
- (void)enumerateIconsUsingBlockWithIndexes:(id)arg1;
- (void)removeIcons:(id)arg1 fromIconsAtPosition:(unsigned long long)arg2;
- (void)removeIcon:(id)arg1 fromIconsAtPosition:(unsigned long long)arg2;
- (void)addIcon:(id)arg1 toIconsAtPosition:(unsigned long long)arg2 atIndex:(unsigned long long)arg3;
- (void)addIcon:(id)arg1 toIconsAtPosition:(unsigned long long)arg2;
- (void)addIcons:(id)arg1 toIconsAtPosition:(unsigned long long)arg2;
- (struct STKGroupSlot)slotForIcon:(id)arg1;
- (void)setIcon:(id)arg1 inSlot:(struct STKGroupSlot)arg2;
- (id)iconInSlot:(struct STKGroupSlot)arg1;
- (id)allIcons;
- (id)iconDictionary;
- (id)identifierDictionary;
- (void)dealloc;
- (id)description;
- (id)init;
- (id)initWithIconsAtTop:(id)arg1 bottom:(id)arg2 left:(id)arg3 right:(id)arg4;
- (id)initWithIconDictionary:(id)arg1;
- (id)initWithIdentifierDictionary:(id)arg1;

@end

