/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface STKGroupLayoutHandler : NSObject
{
}

+ (id)_iconsInRow:(long long)arg1;
+ (id)_iconsInColumn:(long long)arg1;
+ (id)_iconsRightOfIcon:(id)arg1;
+ (id)_iconsLeftOfIcon:(id)arg1;
+ (id)_iconsBelowIcon:(id)arg1;
+ (id)_iconsAboveIcon:(id)arg1;
+ (id)_processLayoutForSymmetry:(id)arg1 withLocation:(unsigned long long)arg2;
+ (id)placeholderLayoutForGroup:(id)arg1;
+ (id)emptyLayoutForIconAtLocation:(unsigned long long)arg1;
+ (unsigned long long)locationForIcon:(id)arg1;
+ (struct SBIconCoordinate)coordinateForIcon:(id)arg1;
+ (id)layoutForIconsToHideAboveDockedIcon:(id)arg1 usingLayout:(id)arg2 targetFrameProvider:(id)arg3;
+ (id)layoutForIconsToDisplaceAroundIcon:(id)arg1 usingLayout:(id)arg2;
+ (id)correctLayoutForGroupIfNecessary:(id)arg1;
+ (id)layoutForIcons:(id)arg1 aroundIconAtLocation:(unsigned long long)arg2;

@end

