/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@class NSDictionary, NSHashTable, SBIcon, STKGroupLayout;

@interface STKGroup : NSObject
{
    STKGroupLayout *_layout;
    STKGroupLayout *_placeholderLayout;
    NSHashTable *_observers;
    SBIcon *_centralIcon;
    long long _state;
    //struct SBIconCoordinate _lastKnownCoordinate;
}

@property(nonatomic) long long state; // @synthesize state=_state;
//@property(nonatomic) struct SBIconCoordinate lastKnownCoordinate; // @synthesize lastKnownCoordinate=_lastKnownCoordinate;
@property(readonly, nonatomic) STKGroupLayout *placeholderLayout; // @synthesize placeholderLayout=_placeholderLayout;
@property(readonly, nonatomic) STKGroupLayout *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) SBIcon *centralIcon; // @synthesize centralIcon=_centralIcon;
- (void)_enumerateObserversUsingBlock:(id)arg1 forSelector:(void)arg2;
- (void)_forceUdpateState;
- (void)_updateState;
- (void)removeObserver:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)_editingEnded:(id)arg1;
- (void)finalizeState;
- (void)removePlaceholders;
- (void)addPlaceholders;
- (void)removeIconInSlot:(struct STKGroupSlot)arg1;
- (void)replaceIconInSlot:(struct STKGroupSlot)arg1 withIcon:(id)arg2;
- (void)forceRelayout;
- (void)relayoutForNewCoordinate:(struct SBIconCoordinate)arg1;
@property(readonly, nonatomic) _Bool empty;
@property(readonly, nonatomic) _Bool hasPlaceholders;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)description;
- (void)dealloc;
- (void)_commonInit;
- (id)initWithDictionary:(id)arg1;
- (id)initWithCentralIcon:(id)arg1 layout:(id)arg2;

@end

