/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <UIKit/UIView.h>

#import "STKGroupObserver-Protocol.h"
#import "STKIconViewSource-Protocol.h"
#import "STKGroupViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSSet, SBIconView, STKGroup, STKGroupLayout, UIPanGestureRecognizer, UITapGestureRecognizer;

@interface STKGroupView : UIView <STKGroupObserver, UIGestureRecognizerDelegate>
{
    STKGroup *_group;
    SBIconView *_centralIconView;
    STKGroupLayout *_subappLayout;
    STKGroupLayout *_displacedIconLayout;
    UIPanGestureRecognizer *_panRecognizer;
    UITapGestureRecognizer *_tapRecognizer;
    NSSet *_iconsHiddenForPlaceholders;
    UIView *_topGrabberView;
    UIView *_bottomGrabberView;
    struct CGRect _topGrabberOriginalFrame;
    struct CGRect _bottomGrabberOriginalFrame;
    _Bool _isOpen;
    _Bool _isAnimatingOpen;
    _Bool _isAnimatingClosed;
    _Bool _ignoreRecognizer;
    _Bool _hasVerticalIcons;
    _Bool _isUpwardSwipe;
    double _lastDistanceFromCenter;
    double _targetDistance;
    double _distanceRatio;
    double _currentBandingAllowance;
    long long _recognizerDirection;
    struct {
        unsigned int didMoveToOffset:1;
        unsigned int shouldOpen:1;
        unsigned int willOpen:1;
        unsigned int didOpen:1;
        unsigned int willClose:1;
        unsigned int didClose:1;
    } _delegateFlags;
    _Bool _showPreview;
    _Bool _showGrabbers;
    _Bool _isAnimating;
    unsigned long long _activationMode;
    id <STKGroupViewDelegate> _delegate;
    id <STKIconViewSource> _iconViewSource;
}

+ (void)initialize;
@property(readonly, nonatomic) UIView *bottomGrabberView; // @synthesize bottomGrabberView=_bottomGrabberView;
@property(readonly, nonatomic) UIView *topGrabberView; // @synthesize topGrabberView=_topGrabberView;
@property(readonly, nonatomic) STKGroupLayout *displacedIconLayout; // @synthesize displacedIconLayout=_displacedIconLayout;
@property(readonly, nonatomic) STKGroupLayout *subappLayout; // @synthesize subappLayout=_subappLayout;
@property(readonly, nonatomic) _Bool isAnimating; // @synthesize isAnimating=_isAnimating;
@property(readonly, nonatomic) _Bool isOpen; // @synthesize isOpen=_isOpen;
@property(nonatomic, assign) id <STKIconViewSource> iconViewSource; // @synthesize iconViewSource=_iconViewSource;
@property(nonatomic, assign) id <STKGroupViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, assign) _Bool showGrabbers; // @synthesize showGrabbers=_showGrabbers;
@property(nonatomic, assign) _Bool showPreview; // @synthesize showPreview=_showPreview;
@property(nonatomic, assign) unsigned long long activationMode; // @synthesize activationMode=_activationMode;
@property(retain, nonatomic) STKGroup *group; // @synthesize group=_group;
- (void)_unhideIconsForPlaceholders;
- (void)_hideIconsForPlaceholders;
- (void)groupDidFinalizeState:(id)arg1;
- (void)groupWillRemovePlaceholders:(id)arg1;
- (void)groupDidAddPlaceholders:(id)arg1;
- (void)group:(id)arg1 removedIcon:(id)arg2 inSlot:(struct STKGroupSlot)arg3;
- (void)group:(id)arg1 replacedIcon:(id)arg2 inSlot:(struct STKGroupSlot)arg3 withIcon:(id)arg4;
- (void)groupDidRelayout:(id)arg1;
- (void)_updateTargetDistance;
- (id)_iconViewForIcon:(id)arg1;
- (void)_setAlphaForDisplacedIcons:(double)arg1;
- (void)_setAlpha:(double)arg1 forBadgeAndLabelOfIconView:(id)arg2;
- (void)_setAlphaForOtherIcons:(double)arg1;
- (struct CGPoint)_displacedOriginForIcon:(id)arg1 withPosition:(unsigned long long)arg2;
- (struct CGPoint)_targetOriginForSubappSlot:(struct STKGroupSlot)arg1;
- (void)_performScaleAnimationOnCentralIconFromScale:(double)arg1 toScale:(double)arg2;
- (void)_animateClosedWithCompletion:(id)arg1;
- (void)_animateOpenWithCompletion:(id)arg1;
- (void)_moveGrabbersByDistance:(double)arg1;
- (void)_calculateDistanceRatio;
- (void)_moveSubappsByDistance:(double)arg1 performingTask:(id)arg2;
- (void)_moveDisplacedIconsByDistance:(double)arg1;
- (void)_moveByDistance:(double)arg1 performingBlockOnSubApps:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)_doubleTapped:(id)arg1;
- (void)_adjustScaleAndTransparencyOfSubapp:(id)arg1 inSlot:(struct STKGroupSlot)arg2 forOffset:(double)arg3;
- (void)_panned:(id)arg1;
- (void)_removeGestureRecognizers;
- (void)_addGestureRecognizers;
- (void)_resetDisplacedIconLayout;
- (void)_removeGrabbers;
- (struct CGRect)_iconImageFrame;
- (void)_addGrabbers;
- (void)_positionIconView:(id)arg1 inPosition:(unsigned long long)arg2 isLast:(_Bool)arg3 scaleDown:(_Bool)arg4;
- (void)_setupPreview;
- (void)_reallyConfigureSubappViews;
- (void)_configureSubappViews;
- (void)didMoveToSuperview;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_setDelegateOnCentralIconView;
- (void)resetImageViewScale;
- (id)subappIconViewForIcon:(id)arg1;
- (void)resetLayouts;
- (void)closeWithCompletionHandler:(id)arg1;
- (void)close;
- (void)openWithCompletionHandler:(id)arg1;
- (void)open;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (id)initWithGroup:(id)arg1 iconViewSource:(id)arg2;

@end

