/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol STKGroupObserver <NSObject>

@optional
- (void)groupDidFinalizeState:(id)arg1;
- (void)groupDidRemovePlaceholders:(id)arg1;
- (void)groupWillRemovePlaceholders:(id)arg1;
- (void)groupDidAddPlaceholders:(id)arg1;
- (void)groupDidRelayout:(id)arg1;
- (void)group:(id)arg1 replacedIcon:(id)arg2 inSlot:(struct STKGroupSlot)arg3 withIcon:(id)arg4;
- (void)group:(id)arg1 removedIcon:(id)arg2 inSlot:(struct STKGroupSlot)arg3;
@end

