/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol STKIconViewSource <NSObject>
- (void)groupView:(id)arg1 willRelinquishIconView:(id)arg2;
- (id)groupView:(id)arg1 wantsIconViewForIcon:(id)arg2;
@end

