/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "STKIconViewSource.h"

@class NSMapTable;

@interface STKIconViewRecycler : NSObject <STKIconViewSource>
{
    NSMapTable *_recycledIconViews;
    unsigned long long _maxRecycledIconViews;
}

- (void)groupView:(id)arg1 willRelinquishIconView:(id)arg2;
- (id)groupView:(id)arg1 wantsIconViewForIcon:(id)arg2;
- (void)recycleIconView:(id)arg1;
- (id)iconViewForIcon:(id)arg1;
- (void)dealloc;
- (id)init;

@end

