/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "STKGroupObserver.h"

@class NSArray, NSMutableDictionary;

@interface STKPreferences : NSObject <STKGroupObserver>
{
    NSMutableDictionary *_preferences;
    NSMutableDictionary *_groups;
    NSMutableDictionary *_subappToCentralMap;
    unsigned long long _activationMode;
}

+ (id)sharedPreferences;
@property(readonly, nonatomic) unsigned long long activationMode; // @synthesize activationMode=_activationMode;
- (void)groupDidRelayout:(id)arg1;
- (void)groupDidFinalizeState:(id)arg1;
- (id)_groupStateFromGroups;
- (void)_mapSubappsInGroup:(id)arg1;
- (void)_resetSubappMap;
- (void)_addOrUpdateGroups:(id)arg1;
- (void)_synchronize;
- (id)groupForSubappIcon:(id)arg1;
- (id)groupForCentralIcon:(id)arg1;
- (void)removeGroup:(id)arg1;
- (void)addOrUpdateGroup:(id)arg1;
@property(readonly, nonatomic) NSArray *identifiersForSubappIcons;
@property(nonatomic) _Bool welcomeAlertShown;
@property(readonly, nonatomic) _Bool shouldOpenSpotlightFromStatusBarTap;
@property(readonly, nonatomic) _Bool shouldDisableSearchGesture;
@property(readonly, nonatomic) _Bool shouldHideGrabbers;
@property(readonly, nonatomic) _Bool shouldCloseOnLaunch;
@property(readonly, nonatomic) _Bool shouldShowSummedBadges;
@property(readonly, nonatomic) _Bool shouldShowPreviews;
@property(readonly, nonatomic) _Bool shouldLockLayouts;
- (_Bool)doubleTapEnabled;
- (_Bool)swipeDownEnabled;
- (_Bool)swipeUpEnabled;
- (void)registerDeviceWithAnalytics;
- (void)reloadPreferences;

@end

