/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionReusableView.h"

@class NSString, SBWallpaperEffectView, UILabel;

@interface STKSelectionHeaderView : UICollectionReusableView
{
    SBWallpaperEffectView *_wallpaperEffectView;
    UILabel *_titleLabel;
}

@property(copy, nonatomic) NSString *headerTitle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

