/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UITextFieldDelegate.h"

@class NSArray, SBFolderBackgroundView, SBIcon, SBIconView, STKSelectionTitleTextField, UICollectionView, UITextField;

@interface STKSelectionView : UIView <UICollectionViewDelegateFlowLayout, UICollectionViewDataSource, UITextFieldDelegate>
{
    UIView *_contentView;
    UICollectionView *_collectionView;
    SBFolderBackgroundView *_backgroundView;
    SBIcon *_selectedIcon;
    SBIcon *_centralIcon;
    SBIconView *_selectedIconView;
    STKSelectionTitleTextField *_searchTextField;
    NSArray *_recommendedApps;
    NSArray *_allApps;
    NSArray *_searchResults;
    _Bool _hasRecommendations;
    _Bool _isSearching;
    NSArray *_iconsForSelection;
    id _selectionHandler;
}

@property(copy, nonatomic) id selectionHandler; // @synthesize selectionHandler=_selectionHandler;
@property(readonly, nonatomic) SBFolderBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) UITextField *searchTextField; // @synthesize searchTextField=_searchTextField;
@property(readonly, nonatomic) SBIcon *selectedIcon; // @synthesize selectedIcon=_selectedIcon;
@property(copy, nonatomic) NSArray *iconsForSelection; // @synthesize iconsForSelection=_iconsForSelection;
- (id)_attributedPlaceholderForTextField;
- (void)_adjustTextFieldBackground;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)_searchTextChanged;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)_setupTextField;
- (void)_selectedCell:(id)arg1;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)_iconsForSection:(long long)arg1;
- (void)_processIcons:(id)arg1;
- (void)dismissKeyboard;
- (void)flashScrollIndicators;
- (void)scrollToSelectedIconAnimated:(_Bool)arg1;
@property(readonly, nonatomic) _Bool isKeyboardVisible;
@property(readonly, nonatomic) UIView *iconCollectionView;
@property(readonly, nonatomic) UIView *contentView;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 selectedIcon:(id)arg2 centralIcon:(id)arg3;

@end

