/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "UICollectionViewCell.h"

#import "SBIconViewDelegate.h"

@class SBIconView;

@interface STKSelectionViewCell : UICollectionViewCell <SBIconViewDelegate>
{
    SBIconView *_iconView;
    id _tapHandler;
}

@property(copy, nonatomic) id tapHandler; // @synthesize tapHandler=_tapHandler;
@property(readonly, nonatomic) SBIconView *iconView; // @synthesize iconView=_iconView;
- (void)iconHandleLongPress:(id)arg1;
- (void)iconTouchBegan:(id)arg1;
- (void)icon:(id)arg1 touchMoved:(id)arg2;
- (void)icon:(id)arg1 touchEnded:(_Bool)arg2;
- (_Bool)iconShouldAllowTap:(id)arg1;
- (void)layoutSubviews;
- (void)iconTapped:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

