ARCHS = armv7 armv7s arm64
include theos/makefiles/common.mk

BUNDLE_NAME = GlowBoardFlipswitch
GlowBoardFlipswitch_FILES = Switch.x
GlowBoardFlipswitch_FRAMEWORKS = UIKit
GlowBoardFlipswitch_LIBRARIES = flipswitch
GlowBoardFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk